#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xffe5;
constexpr uint24_t FX_DATA_BYTES = 6747;

constexpr uint24_t vaultboy = 0x000000;
constexpr uint16_t vaultboyWidth  = 31;
constexpr uint16_t vaultboyHeight = 60;
constexpr uint8_t  vaultboyFrames = 8;

constexpr uint24_t radiograph = 0x0007C4;
constexpr uint16_t radiographWidth  = 32;
constexpr uint16_t radiographHeight = 32;

constexpr uint24_t houston = 0x000848;
constexpr uint16_t houstonWidth  = 128;
constexpr uint16_t houstonHeight = 64;

constexpr uint24_t tinyFont = 0x000C4C;
constexpr uint16_t tinyFontWidth  = 5;
constexpr uint16_t tinyFontHeight = 4;
constexpr uint8_t  tinyFontFrames = 124;

constexpr uint24_t arduboyFont = 0x000EBC;
constexpr uint16_t arduboyFontWidth  = 6;
constexpr uint16_t arduboyFontHeight = 8;
constexpr uint16_t  arduboyFontFrames = 256;

constexpr uint24_t eachlife = 0x0014C0;
constexpr uint24_t crawlout = 0x00151E;
constexpr uint24_t test = 0x001664;
constexpr uint24_t splashnum = 0x001672;
constexpr uint24_t inventorylist = 0x001679;
constexpr uint24_t Lock = 0x0016A0;
constexpr uint24_t Key = 0x0016D8;
constexpr uint24_t Cache = 0x001706;
constexpr uint24_t WinUSB = 0x00171C;
constexpr uint24_t LinUSB = 0x00172D;
constexpr uint24_t GC = 0x00173E;
constexpr uint24_t lockout = 0x00174E;
constexpr uint24_t toggleWin = 0x00175B;
constexpr uint24_t openTerm = 0x00176B;
constexpr uint24_t life = 0x00177C;
constexpr uint24_t crawl = 0x00178B;
constexpr uint24_t bul1 = 0x001795;
constexpr uint24_t bul2 = 0x0017A4;
constexpr uint24_t bul3 = 0x0017B0;
constexpr uint24_t bul4 = 0x0017C5;
constexpr uint24_t bul5 = 0x0017D6;
constexpr uint24_t bul6 = 0x0017E6;
constexpr uint24_t bul8 = 0x00182E;
constexpr uint24_t bul9 = 0x001889;
constexpr uint24_t exitstring = 0x00188B;
constexpr uint24_t buw1 = 0x001890;
constexpr uint24_t buw2 = 0x00189B;
constexpr uint24_t buw3 = 0x0018C0;
constexpr uint24_t buw4 = 0x0018FE;
