#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xffc6;
constexpr uint24_t FX_DATA_BYTES = 14636;

constexpr uint24_t vaultboy = 0x000000;
constexpr uint16_t vaultboyWidth  = 31;
constexpr uint16_t vaultboyHeight = 60;
constexpr uint8_t  vaultboyFrames = 8;

constexpr uint24_t radiograph = 0x0007C4;
constexpr uint16_t radiographWidth  = 32;
constexpr uint16_t radiographHeight = 32;

constexpr uint24_t houston = 0x000848;
constexpr uint16_t houstonWidth  = 128;
constexpr uint16_t houstonHeight = 64;

constexpr uint24_t portland = 0x000C4C;
constexpr uint16_t portlandWidth  = 128;
constexpr uint16_t portlandHeight = 64;

constexpr uint24_t losangeles = 0x001050;
constexpr uint16_t losangelesWidth  = 128;
constexpr uint16_t losangelesHeight = 64;

constexpr uint24_t tinyFont = 0x001454;
constexpr uint16_t tinyFontWidth  = 5;
constexpr uint16_t tinyFontHeight = 4;
constexpr uint8_t  tinyFontFrames = 124;

constexpr uint24_t arduboyFont = 0x0016C4;
constexpr uint16_t arduboyFontWidth  = 6;
constexpr uint16_t arduboyFontHeight = 8;
constexpr uint16_t  arduboyFontFrames = 256;

constexpr uint24_t anythinggoes = 0x001CC8;
constexpr uint24_t anything_Len = 0x0024C5;
constexpr uint24_t johnnyguitar = 0x0024C7;
constexpr uint24_t johnny_Len = 0x002A2C;
constexpr uint24_t kick = 0x002A2E;
constexpr uint24_t kick_Len = 0x003384;
constexpr uint24_t test = 0x003386;
constexpr uint24_t splashnum = 0x003394;
constexpr uint24_t inventorylist = 0x00339B;
constexpr uint24_t Lock = 0x0033C2;
constexpr uint24_t Key = 0x0033FA;
constexpr uint24_t Cache = 0x003428;
constexpr uint24_t BadUSB = 0x00343E;
constexpr uint24_t WinUSB = 0x00344C;
constexpr uint24_t fork = 0x00345A;
constexpr uint24_t LinUSB = 0x003467;
constexpr uint24_t GC = 0x003478;
constexpr uint24_t macs = 0x003488;
constexpr uint24_t lockout = 0x003493;
constexpr uint24_t toggleWin = 0x0034A0;
constexpr uint24_t openTerm = 0x0034B0;
constexpr uint24_t seria = 0x0034C1;
constexpr uint24_t sterm = 0x0034C8;
constexpr uint24_t splot = 0x0034D1;
constexpr uint24_t anything = 0x0034D9;
constexpr uint24_t johnny = 0x0034E7;
constexpr uint24_t head = 0x0034F5;
constexpr uint24_t bul1 = 0x003507;
constexpr uint24_t bul2 = 0x003516;
constexpr uint24_t bul3 = 0x003522;
constexpr uint24_t bul4 = 0x003537;
constexpr uint24_t bul5 = 0x003548;
constexpr uint24_t bul6 = 0x003558;
constexpr uint24_t bul8 = 0x0035A0;
constexpr uint24_t bul9 = 0x0035FB;
constexpr uint24_t exitstring = 0x0035FD;
constexpr uint24_t buw1 = 0x003602;
constexpr uint24_t buw2 = 0x00360D;
constexpr uint24_t buw3 = 0x003632;
constexpr uint24_t buw4 = 0x003670;
constexpr uint24_t ytlink = 0x0037CD;
constexpr uint24_t roll = 0x0037F5;
constexpr uint24_t bfb1 = 0x003802;
constexpr uint24_t bfb2 = 0x003806;
constexpr uint24_t bfb3 = 0x003820;
constexpr uint24_t bfb4 = 0x003829;
