#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xffbe;
constexpr uint24_t FX_DATA_BYTES = 16725;

constexpr uint24_t vaultboy = 0x000000;
constexpr uint16_t vaultboyWidth  = 31;
constexpr uint16_t vaultboyHeight = 60;
constexpr uint8_t  vaultboyFrames = 8;

constexpr uint24_t radiograph = 0x0007C4;
constexpr uint16_t radiographWidth  = 32;
constexpr uint16_t radiographHeight = 32;

constexpr uint24_t houston = 0x000848;
constexpr uint16_t houstonWidth  = 128;
constexpr uint16_t houstonHeight = 64;

constexpr uint24_t portland = 0x000C4C;
constexpr uint16_t portlandWidth  = 128;
constexpr uint16_t portlandHeight = 64;

constexpr uint24_t losangeles = 0x001050;
constexpr uint16_t losangelesWidth  = 128;
constexpr uint16_t losangelesHeight = 64;

constexpr uint24_t tinyFont = 0x001454;
constexpr uint16_t tinyFontWidth  = 5;
constexpr uint16_t tinyFontHeight = 4;
constexpr uint8_t  tinyFontFrames = 124;

constexpr uint24_t voidlogo = 0x0016C4;
constexpr uint16_t voidlogoWidth  = 128;
constexpr uint16_t voidlogoHeight = 64;

constexpr uint24_t arduboyFont = 0x001EC8;
constexpr uint16_t arduboyFontWidth  = 6;
constexpr uint16_t arduboyFontHeight = 8;
constexpr uint16_t  arduboyFontFrames = 256;

constexpr uint24_t anythinggoes = 0x0024CC;
constexpr uint24_t anything_Len = 0x002CC9;
constexpr uint24_t johnnyguitar = 0x002CCB;
constexpr uint24_t johnny_Len = 0x003230;
constexpr uint24_t kick = 0x003232;
constexpr uint24_t kick_Len = 0x003B88;
constexpr uint24_t test = 0x003B8A;
constexpr uint24_t splashnum = 0x003B98;
constexpr uint24_t inventorylist = 0x003B9F;
constexpr uint24_t Lock = 0x003BC6;
constexpr uint24_t Key = 0x003BFE;
constexpr uint24_t Cache = 0x003C2C;
constexpr uint24_t BadUSB = 0x003C42;
constexpr uint24_t WinUSB = 0x003C50;
constexpr uint24_t fork = 0x003C5E;
constexpr uint24_t LinUSB = 0x003C6B;
constexpr uint24_t GC = 0x003C7C;
constexpr uint24_t macs = 0x003C8C;
constexpr uint24_t lockout = 0x003C97;
constexpr uint24_t toggleWin = 0x003CA4;
constexpr uint24_t openTerm = 0x003CB4;
constexpr uint24_t seria = 0x003CC5;
constexpr uint24_t sterm = 0x003CCC;
constexpr uint24_t splot = 0x003CD5;
constexpr uint24_t osci = 0x003CDD;
constexpr uint24_t mica = 0x003CEE;
constexpr uint24_t micb = 0x003CF8;
constexpr uint24_t anything = 0x003D02;
constexpr uint24_t johnny = 0x003D10;
constexpr uint24_t head = 0x003D1E;
constexpr uint24_t bul1 = 0x003D30;
constexpr uint24_t bul2 = 0x003D3F;
constexpr uint24_t bul3 = 0x003D4B;
constexpr uint24_t bul4 = 0x003D60;
constexpr uint24_t bul5 = 0x003D71;
constexpr uint24_t bul6 = 0x003D81;
constexpr uint24_t bul8 = 0x003DC9;
constexpr uint24_t bul9 = 0x003E24;
constexpr uint24_t exitstring = 0x003E26;
constexpr uint24_t buw1 = 0x003E2B;
constexpr uint24_t buw2 = 0x003E36;
constexpr uint24_t buw3 = 0x003E5B;
constexpr uint24_t buw4 = 0x003E99;
constexpr uint24_t ytlink = 0x003FF6;
constexpr uint24_t roll = 0x00401E;
constexpr uint24_t bfb1 = 0x00402B;
constexpr uint24_t bfb2 = 0x00402F;
constexpr uint24_t bfb3 = 0x004049;
constexpr uint24_t bfb4 = 0x004052;
